### ISSUE TITLE
Start off completely closed?

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/paragraphs_jquery_ui_accordion#1]
Would it be possible to have a setting that allowed the accordion to start off completely closed instead of the first one being opened automatically?

**Comment by laryn** [comment]
This request was also made in the D7 version, and there is a patch there:

 - https://www.drupal.org/project/paragraphs_jquery_ui_accordion/issues/3139221

**Comment by alanmels** [comment]
Sorry, somehow missed this issue. Incorporating the suggested changes.

**Comment by alanmels** [comment]
Have to re-open this as the changes made cause:

`
Notice: Undefined index: startclosed in paragraphs_jquery_ui_accordion_field_formatter_view() (line 116 of /var/www/html/docroot/modules/paragraphs_jquery_ui_accordion/paragraphs_jquery_ui_accordion.module). 
`
