### ISSUE TITLE
Unpublished item in accordion is still showing up for site visitors

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/paragraphs_jquery_ui_accordion#20]
Here is a screenshot from a client site. 

![image](https://github.com/user-attachments/assets/fb0d0fa4-bfa5-4279-9ae8-547b3991e33b)

Accordion items are showing up, even if they are unpublished.

**Comment by stpaultim** [comment]
@Abid05 has created a PR. I believe the PR is just checking to see if the paragraph is published before posting it?

Is that correct @Abid05 ?

**Comment by yorkshire-pudding** [comment]
@stpaultim - thanks for clarifying this.
@Abid05 - thanks - I have commented on the PR.
