### ISSUE TITLE
Notice: Trying to access array offset on value of type null 

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/paragraphs_jquery_ui_accordion#6]
We are seeing this notice in a site.

`
Notice: Trying to access array offset on value of type null in paragraphs_jquery_ui_accordion_field_formatter_view() (line 145 of .../modules/contrib/paragraphs_jquery_ui_accordion/paragraphs_jquery_ui_accordion.module).
`

We have not had time to debug this or provide additional information. But, opening ticket in case others are seeing anything similar. I'll try to provide more information as we look deeper into this issue.

**Comment by alanmels** [comment]
Hi @stpaultim,

Unfortunately, I couldn't replicate the issue, so would appreciate if you could share your setup and give pointers on how to replicate the error.

**Comment by stpaultim** [comment]
@alanmels - I'll ask my colleagues if we are still getting this error. This might not be an issue anymore.

**Comment by stpaultim** [comment]
@alanmels - I'm going to go ahead and close this issue. I'm not seeing the issue in the logs anymore. It may have been bi-product of something else.
